baseurl = "http://r9y9.github.io/"
languageCode = "ja-jp"
title = "LESS IS MORE"
author = "Ryuichi YAMAMOTO"

[permalinks]
    post = "/blog/:year/:month/:day/:filename/"

[params]
  author    = "Ryuichi YAMAMOTO"
  bio       = "fmt.Println(\"Hello world!\")"
  logo      = "/images/r9y9.jpg"
  copyright = "Ryuichi YAMAMOTO All rights reserved."
  twitter   = "r9y9"
  github    = "r9y9"
  analytics = "UA-44433856-1"
