baseurl = "http://r9y9.github.io/"
DefaultContentLanguage = "ja"
languageCode = "ja-jp"
title = "LESS IS MORE"
author = "Ryuichi YAMAMOTO"

[permalinks]
    post = "/blog/:year/:month/:day/:filename/"

[params]
  author    = "Ryuichi YAMAMOTO"
  logo      = "/images/r9y9.jpg"
  twitter   = "r9y9"
  github    = "r9y9"
  analytics = "UA-44433856-1"
